- name: Checkout
  uses: actions/checkout@v4

- name: Use Node
  uses: actions/setup-node@v4
  with:
    node-version: 22.x
    cache: 'npm'

- name: Create .env
  run: |
    cat <<'EOF' > .env
    PORT_SERVER=${{ secrets.PORT_SERVER }}
    DB_USERNAME=${{ secrets.DB_USERNAME }}
    DB_PASSWORD=${{ secrets.DB_PASSWORD }}
    AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
    AWS_BUCKET_ACCESS_KEY=${{ secrets.AWS_BUCKET_ACCESS_KEY }}
    AWS_BUCKET_SECRET_KEY=${{ secrets.AWS_BUCKET_SECRET_KEY }}
    CLOUDFRONT_PUBLIC_KEY_GROUPS_ID=${{ secrets.CLOUDFRONT_PUBLIC_KEY_GROUPS_ID }}
    CLOUDFRONT_PRIVATE_KEY=${{ secrets.CLOUDFRONT_PRIVATE_KEY }}
    EOF
    # Nếu dùng \n escaped:
    perl -0777 -pe 's/CLOUDFRONT_PRIVATE_KEY=\K.*/(my $v=$&)=~s#\\n#\n#gr/e' -i .env

- name: Install
  run: npm ci

- name: Build
  run: npm run build

- name: PM2 start or reload (ecosystem)
  run: |
    if pm2 describe shopDev-be > /dev/null; then
      pm2 reload ecosystem.config.js
    else
      pm2 start ecosystem.config.js
    fi
    pm2 save
